// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp8K8praNbQu5y9uJKivSES7Ee5_sLjaA',
    appId: '1:1073351466302:web:9050abde6730faf2c8606f',
    messagingSenderId: '1073351466302',
    projectId: 'esacc-44037',
    authDomain: 'esacc-44037.firebaseapp.com',
    storageBucket: 'esacc-44037.firebasestorage.app',
    measurementId: 'G-KTXTEJLNE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk5iU3qX9yDzdQOxdWKMP-vd0pG-0KXsY',
    appId: '1:1073351466302:android:25b02be33de56d15c8606f',
    messagingSenderId: '1073351466302',
    projectId: 'esacc-44037',
    storageBucket: 'esacc-44037.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe1ACq63-r0qScoMZrEB86CR-i6w_12L8',
    appId: '1:1073351466302:ios:b767b2dfb4691deac8606f',
    messagingSenderId: '1073351466302',
    projectId: 'esacc-44037',
    storageBucket: 'esacc-44037.firebasestorage.app',
    iosBundleId: 'com.example.esacc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe1ACq63-r0qScoMZrEB86CR-i6w_12L8',
    appId: '1:1073351466302:ios:b767b2dfb4691deac8606f',
    messagingSenderId: '1073351466302',
    projectId: 'esacc-44037',
    storageBucket: 'esacc-44037.firebasestorage.app',
    iosBundleId: 'com.example.esacc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp8K8praNbQu5y9uJKivSES7Ee5_sLjaA',
    appId: '1:1073351466302:web:66933b467c0c0c96c8606f',
    messagingSenderId: '1073351466302',
    projectId: 'esacc-44037',
    authDomain: 'esacc-44037.firebaseapp.com',
    storageBucket: 'esacc-44037.firebasestorage.app',
    measurementId: 'G-4NRN0ZBDDP',
  );
}
